In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn import feature_extraction, linear_model, model_selection, preprocessing
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [11]:
fake = pd.read_csv("D:\\VARSHITHA\\fake news detection\\Fake.csv", dtype=str)
true = pd.read_csv("D:\\VARSHITHA\\fake news detection\\True.csv", dtype=str)

In [12]:
fake.shape

(23481, 4)

In [13]:
true.shape

(21417, 4)

In [14]:
# Add flag to track fake and real
fake['target'] = 'fake'
true['target'] = 'true'

In [15]:
# Concatenate dataframes
data = pd.concat([fake, true]).reset_index(drop = True)
data.shape

(44898, 5)

In [16]:
# Shuffle the data
from sklearn.utils import shuffle
data = shuffle(data)
data = data.reset_index(drop=True)

In [17]:
# Check the data
data.head()

,title,text,subject,date,target
0,Trump Humiliated By Being Forced To Sign Russ...,Amateur president Donald Trump signed was for...,News,"August 2, 2017",fake
1,"In meeting, Trump to push a reluctant Xi to re...",WASHINGTON (Reuters) - President Donald Trump ...,politicsNews,"November 1, 2017",true
2,Exposing the Shakespearean tragedy of the “Rus...,Sunday Wire host Patrick Henningsen delivers a...,US_News,"November 18, 2017",fake
3,IS JADE HELM 15 REALLY ABOUT MARTIAL LAW? Texa...,Chuck Norris wrote about Jade Helm 15 in a com...,left-news,"May 6, 2015",fake
4,Trump’s Idiot Press Secretary Tweeted Out His...,When President Asterisk assured us he was asse...,News,"January 26, 2017",fake

In [18]:
# Removing the date (we won't use it for the analysis)
data.drop(["date"],axis=1,inplace=True)
data.head()

,title,text,subject,target
0,Trump Humiliated By Being Forced To Sign Russ...,Amateur president Donald Trump signed was for...,News,fake
1,"In meeting, Trump to push a reluctant Xi to re...",WASHINGTON (Reuters) - President Donald Trump ...,politicsNews,true
2,Exposing the Shakespearean tragedy of the “Rus...,Sunday Wire host Patrick Henningsen delivers a...,US_News,fake
3,IS JADE HELM 15 REALLY ABOUT MARTIAL LAW? Texa...,Chuck Norris wrote about Jade Helm 15 in a com...,left-news,fake
4,Trump’s Idiot Press Secretary Tweeted Out His...,When President Asterisk assured us he was asse...,News,fake

In [19]:
# Removing the title (we will only use the text)
data.drop(["title"],axis=1,inplace=True)
data.head()

                                                text       subject target
0  Amateur president Donald Trump  signed was for...          News   fake
1  WASHINGTON (Reuters) - President Donald Trump ...  politicsNews   true
2  Sunday Wire host Patrick Henningsen delivers a...       US_News   fake
3  Chuck Norris wrote about Jade Helm 15 in a com...     left-news   fake
4  When President Asterisk assured us he was asse...          News   fake

In [20]:
# Convert to lowercase

data['text'] = data['text'].apply(lambda x: x.lower())
data.head()

                                                text       subject target
0  amateur president donald trump  signed was for...          News   fake
1  washington (reuters) - president donald trump ...  politicsNews   true
2  sunday wire host patrick henningsen delivers a...       US_News   fake
3  chuck norris wrote about jade helm 15 in a com...     left-news   fake
4  when president asterisk assured us he was asse...          News   fake

In [21]:
# Remove punctuation

import string

def punctuation_removal(text):
    all_list = [char for char in text if char not in string.punctuation]
    clean_str = ''.join(all_list)
    return clean_str

data['text'] = data['text'].apply(punctuation_removal)

In [22]:
# Check
data.head()

                                                text       subject target
0  amateur president donald trump  signed was for...          News   fake
1  washington reuters  president donald trump wil...  politicsNews   true
2  sunday wire host patrick henningsen delivers a...       US_News   fake
3  chuck norris wrote about jade helm 15 in a com...     left-news   fake
4  when president asterisk assured us he was asse...          News   fake

In [ ]:
# Removing stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

data['text'] = data['text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [ ]:
data.head()